version: '3'
services:
   multitor:
         build: .
         ports:
           - "9050:9050"
           - "9051:9051"
           - "9052:9052"
           - "9053:9053"
           - "9054:9054"
           - "16379:16379"
